name: Website Continuous Integration

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm run build
      - run: ls
      - run: pwd 
      - name: copy file via ssh password
        uses: garygrossgarten/github-action-scp@release
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          recursive: true
          local: "/home/runner/work/wokaround-site/wokaround-site/build/"
          remote: "src/build"

